cc_library(
    name = "heavy_lifter_lib",
    srcs = [
        "heavy_lifter.cpp",
    ],
    hdrs = [
        "heavy_lifter.h",
    ],
    copts = ["--std=c++17"],
    visibility = ["//visibility:public"],
    deps = [
        "@com_google_glog//:glog",
    ],
)
